import { ReactNode } from 'react'
import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '500', '900'],
  variable: '--font-mulish',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} font-sans`}>{children}</body>
    </html>
  )
}
